---
- name: Install
  become: yes
  apt:
    name: nginx
    state: latest

- name: start
  become: yes
  service: 
    name: nginx
    state: started
    enabled: true

- name: suprimmer default.conf
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: nginx reload

- name: NodeJS
  become: yes
  include: node.yml

- name: Configuration des sites
  become: yes
  include: site.yml
  with_items: "{{ domains }}"
...