---
- name:  Installation des serveurs web
  hosts: web
  remote_user: root
  vars:
    user: volibear
    domains: 
      - '192.168.122.9'
      - '192.168.122.47'

  

  roles:
    - user
    - utils
    - nginx
...