---
- name: Intallation de nodeJS
  apt:
    update_cache: yes
    pkg:
      - nodejs
      - npm


- name: Ajout liens pour fonctionnement node
  file:
    src: /usr/bin/nodejs
    dest: /usr/local/bin/node
    state: link
  file:
    src: /usr/bin/npm
    dest: /usr/local/bin/npm
    state: link
...